export GPG_TTY=$(tty)
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dversion=1.16.7 -Dpackaging=aar -DpomFile=brandmessengercommons-1.16.7.pom -Dfile=brandmessengercommons-1.16.7.aar
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercommons-1.16.7.pom -Dfile=brandmessengercommons-1.16.7-sources.jar -Dclassifier=sources
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercommons-1.16.7.pom -Dfile=brandmessengercommons-1.16.7-javadoc.jar -Dclassifier=javadoc

mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dversion=1.16.7 -Dpackaging=aar -DpomFile=brandmessengercore-1.16.7.pom -Dfile=brandmessengercore-1.16.7.aar
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercore-1.16.7.pom -Dfile=brandmessengercore-1.16.7-sources.jar -Dclassifier=sources
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercore-1.16.7.pom -Dfile=brandmessengercore-1.16.7-javadoc.jar -Dclassifier=javadoc

mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dversion=1.16.7 -Dpackaging=aar -DpomFile=brandmessengerui-1.16.7.pom -Dfile=brandmessengerui-1.16.7.aar
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengerui-1.16.7.pom -Dfile=brandmessengerui-1.16.7-sources.jar -Dclassifier=sources
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengerui-1.16.7.pom -Dfile=brandmessengerui-1.16.7-javadoc.jar -Dclassifier=javadoc