export GPG_TTY=$(tty)
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dversion=2.0.1 -Dpackaging=aar -DpomFile=brandmessengercommons-2.0.1.pom -Dfile=brandmessengercommons-2.0.1.aar
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercommons-2.0.1.pom -Dfile=brandmessengercommons-2.0.1-sources.jar -Dclassifier=sources
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercommons-2.0.1.pom -Dfile=brandmessengercommons-2.0.1-javadoc.jar -Dclassifier=javadoc

mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dversion=2.0.1 -Dpackaging=aar -DpomFile=brandmessengercore-2.0.1.pom -Dfile=brandmessengercore-2.0.1.aar
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercore-2.0.1.pom -Dfile=brandmessengercore-2.0.1-sources.jar -Dclassifier=sources
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengercore-2.0.1.pom -Dfile=brandmessengercore-2.0.1-javadoc.jar -Dclassifier=javadoc

mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dversion=2.0.1 -Dpackaging=aar -DpomFile=brandmessengerui-2.0.1.pom -Dfile=brandmessengerui-2.0.1.aar
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengerui-2.0.1.pom -Dfile=brandmessengerui-2.0.1-sources.jar -Dclassifier=sources
mvn gpg:sign-and-deploy-file -Durl=https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/ -DrepositoryId=central -Dpackaging=jar -DpomFile=brandmessengerui-2.0.1.pom -Dfile=brandmessengerui-2.0.1-javadoc.jar -Dclassifier=javadoc